export const BUSINESS_RULES = {
  OPENERS_PER_DAY: 2,
  CLOSERS_PER_DAY: 2,

  TARGET_HOURS: 40,

  DAYS_OFF_PER_WEEK: 1,

  SATURDAYS_OFF_PER_MONTH: 1,

  JUSTIN_SATURDAYS_OFF_PER_MONTH: 2,

  ROTATE_MONDAY_CLOSES: true,
  ROTATE_FRIDAY_CLOSES: true,
  ROTATE_SATURDAY_CLOSES: true,

  JUSTIN_IS_BUFFER: true,
};